### PR TITLE
Add System Python UDF documentation

### PR DESCRIPTION
**Pull request by Krock21**
Added Python UDF documentation under Query Tracker section. Checked locally

### CODE REVIEW

**Comment by Krisha11** [comment]
LGTM

**Review by ogorbacheva — APPROVED** [review]
OK

**Review by Krisha11 — APPROVED** [review]

**Comment by Krisha11** [comment]
Why are we putting this in query_tracker chapter and not in the yql one?

**Comment by Krock21** [comment]
> Why are we putting this in query_tracker chapter and not in the yql one?

We agreed that I will put it here as the best place available for external people

YQL documentation is special. It's source of truth is combined from ydb repository and internal Yandex repository. YT specific things are not included in ydb repository so the only thing that left for yt-specific YQL things in internal Yandex repository.

Later this part can be moved to a better place. cc @ogorbacheva @blinkov

**Pull request closed without merging**
