### PR TITLE
Fix controller agent common operation options config

### PR DESCRIPTION
**Pull request by koct9i**
"operation_options" works as patch for all operation options.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

**Comment by koct9i** [comment]
Please cherry-pick into stable branches.

**Comment by gritukan** [comment]
LGTM, let's wait for someone to run tests.

**Review by gritukan — APPROVED** [review]

**Review by chizhonkova — APPROVED** [review]

**Comment by chizhonkova** [comment]
These tests failed:
1. test_scheduler_operation_lifecycle.py::TestSchedulerAttributes test_specs
2. test_scheduler_config.py::TestSchedulerConfig test_cypress_config

3. test_gpu_layers.py::TestGpuCheck test_gpu_check_success
4. test_layers.py::TestDockerImage test_docker_image_success
5. test_user_job.py::TestSlotManagerResurrect test_job_env_resurrect_with_volume_and_container_leak

**Comment by koct9i** [comment]
Ok this patch is wrong.
"operation_options" must not override type-specific options.
It must override defaults.

**Comment by koct9i** [comment]
Later

**Pull request closed without merging**
