### PR TITLE
Data nodes disk throttlers for uncategorized load

### PR DESCRIPTION
**Pull request by Krock21**
Replace unlimited disk throttlers with uncategorized disk throttlers that:
- combine in and out load
- are configurable

Please cherry-pick it to stable/23.2 and stable/24.1

### CODE REVIEW

**Review by gritukan — APPROVED** [review]

**Comment by psushin** [comment]
Shipped!

**Comment by psushin** [comment]
Ok, this seems dangerous, but reasonable for cases, when one wants to keep the total disk load well below it's physical limits.

**Comment by Krock21** [comment]
> Ok, this seems dangerous, but reasonable for cases, when one wants to keep the total disk load well below it's physical limits.

This was our case. Our exec and data nodes share the same disk, and we saw that jobs struggle in the "spawning job proxy" stage because data nodes utilized the whole disk

We used network throttlers to limit the load, but it limits all disks on data nodes which is bad for performance

Throttlers in this PR allow fine grained throttling per disk

**Comment by psushin** [comment]
Сherry-picked to stable/23.2 and stable/24.1

**Pull request closed without merging**
