### PR TITLE
Add ya package for ytsaurus local docker image

### PR DESCRIPTION
**Pull request by koct9i**
- Cleanup ytsaurus ya-build docker packages
  
- Add ya package for ytsaurus-local

### CODE REVIEW

**Comment by koct9i** [comment]
"docker_target" in package.json does not work as expected due to
https://github.com/yandex/yatool/issues/18

**Comment by koct9i** [comment]
I'll update this when ya-package will be available

**Comment by koct9i** [comment]
@savnadya done, fixed ya package already in main

**Comment by savnadya** [comment]
Shipped!

**Pull request closed without merging**
