### PR TITLE
Increment timeout counter on dns resolve timeout

### PR DESCRIPTION
**Pull request by kaikash**
Seems to be a bug, `TimeoutCounter` is created in `TDnsResolver` but never incremented.

### CODE REVIEW

**Review by Kontakter — APPROVED** [review]

**Comment by achulkov2** [comment]
Hi! Thank you for fixing this!
Let's cherry-pick this into release branches (both 24.1 and 23.2)?
There have been multiple occasions on which this sensor would have helped us in our installations, and I was thinking of adding this functionality myself. 

Would either @kaikash or @Kontakter be willing to do this?

**Comment by kaikash** [comment]
I think I don’t have enough permissions to cherry-pick to stable branches.

**Comment by achulkov2** [comment]
@kaikash you can create pull requests into stable branches the same way you create PRs into main. robot-piglet will be able to import them into the release branch.

**Comment by kaikash** [comment]
@achulkov2 didn't work xd 

https://github.com/ytsaurus/ytsaurus/pull/664

**Comment by achulkov2** [comment]
@kaikash yeah, it won't work if you use the same branch as in the PR.
You have to checkout a new branch from `stable/xx.y`, cherry-pick your commit from `main` into it (it is best to use the final commit produced by robot-piglet) and then create a PR from that branch into `stable/xx.y`.

**Comment by kaikash** [comment]
Cherry-picking this commit into `stable/23.2` and `stable/24.1` is quite challenging since `TAresDnsResolver` was refactored in the `main` branch. This would require cherry-picking a large chain of other commits, and I'm not sure which commits should be cherry-picked and which should not. Perhaps @Kontakter can help with this?

Another approach would be to address this issue with a new commit for the current version of `TAresDnsResolver` in the `stable/xx.y` branches. However, this means that the `main` branch and the `stable/xx.y` branches will diverge.

**Pull request closed without merging**
